### ISSUE TITLE
Doesn't work on Firefox

### ISSUE THREAD

**Issue by lestrobl** [ujw0l/takePicWp#7]
The Plugin throws errors, if trying to use it under firefox/safari:
![image](https://user-images.githubusercontent.com/13135512/104004019-881c3080-51a3-11eb-9e64-ad5c640e70d6.png)

**Comment by ujw0l** [comment]
My understanding is, firefox and sfari do not quite support usermedia (API for webcam), when I am testing some time it works some time it doesnot

**Comment by ujw0l** [comment]
clone the latest one it should work now
